tasks:
  - command: /home/gitpod/elasticsearch-5.5.3/bin/elasticsearch
    # Run ElasticSearch when prebuilding the workspace, so that adventures can be indexed.
    # It has to run in the background so that the prebuild does not wait for it to exit.
    prebuild: /home/gitpod/elasticsearch-5.5.3/bin/elasticsearch &
  - before: gp await-port 9200
    init: |
      mysql -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"
      mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS adl;"
      composer install -n --no-suggest
      php bin/console doctrine:migrations:migrate --no-interaction
      php bin/console doctrine:fixtures:load --no-interaction --fixtures src/AppBundle/DataFixtures/ORM/RandomAdventureData.php --fixtures src/AppBundle/DataFixtures/ORM/TestUserData.php
      php bin/console app:elasticsearch:reindex
    command: php bin/console server:start 0.0.0.0:8000
  - init: npm install
    command: npm run dev-server-gitpod
    openMode: split-right

ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 8002
    onOpen: ignore
  - port: 8003
    onOpen: ignore
  - port: 9200
    onOpen: ignore
  - port: 9222
    onOpen: ignore
  - port: 9300
    onOpen: ignore

image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client@1.3.11:w7xbYI5q5Cfv+1GBejftKg==