<?php

namespace AppBundle\Repository;

/**
 * AdventureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdventureRepository extends \Doctrine\ORM\EntityRepository
{
}
