<?php

namespace AppBundle\Repository;

use AppBundle\Entity\AdventureList;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * AdventureListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdventureListRepository extends EntityRepository
{
    /**
     * @return AdventureList[]
     */
    public function myLists(UserInterface $user = null)
    {
        if (null === $user) {
            return [];
        }

        return $this->findBy(['user' => $user], ['name' => 'ASC']);
    }
}
