<?php

namespace AppBundle\Repository;

/**
 * ChangeRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
