<?php

namespace AppBundle\Repository;

/**
 * ChangeRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeRequestRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function getUnresolvedChangeRequestsQuery()
    {
        $qb = $this->createQueryBuilder('c');

        return $qb
            ->join('c.adventure', 'a')
            ->where($qb->expr()->eq('c.resolved', $qb->expr()->literal(false)))
            ->getQuery();
    }
}
