<?php

namespace AppBundle\Repository;

/**
 * EditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditionRepository extends \Doctrine\ORM\EntityRepository
{
}
