<?php

namespace AppBundle\Repository;

/**
 * MonsterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonsterRepository extends \Doctrine\ORM\EntityRepository
{
    use RelatedEntityFieldValueCountsTrait;
}
