<?php

namespace AppBundle\Repository;

/**
 * NPCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NPCRepository extends \Doctrine\ORM\EntityRepository
{
}
