<?php

namespace AppBundle\Repository;

/**
 * ReviewVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
