<?php

namespace AppBundle\Repository;

/**
 * TagContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagContentRepository extends \Doctrine\ORM\EntityRepository
{
}
