<?php

namespace AppBundle\Repository;

/**
 * TagNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagNameRepository extends \Doctrine\ORM\EntityRepository
{
}
